### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by WhytheFdoIneedanotherusername** [blaxxun-boop/Farming#1]
Hi! Thanks for your mod. I don't know if you're open to requests, but if you are, your mod currently doesn't integrate with Mass Farming - if you're unfamiliar, it allows you to plant/harvest multiple crops at a time while holding a modifier key. Would you please consider adding support for your mod to interact with mass farming, so that experience is awarded based on number of crops planted, rather than number of mouse clicks?

Thanks for your time!

**Comment by blaxxun-boop** [comment]
Mass Farming is now part of Farming, starting at skill level 20.

Nothing I can do about Seed Totem, because that's not you planting the crops.
