### ISSUE TITLE
[BUG] Console spamming the following error

### ISSUE THREAD

**Issue by Reaper0503** [blaxxun-boop/Farming#12]
[Error  : Unity Log] MissingMethodException: void Player.ConsumeResources(Piece/Requirement[],int)
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
Player.Update () (at <89fc507b04c049dea6a613ec7447ff8b>:0)

Planting multiple items also doesn't seem to work. When attempting to plant multiple it shows the multiple plants to be placed however you need to manually click for each one. All other features seem to be working as intended.

**Comment by blaxxun-boop** [comment]
I don't take bug reports for Mistlands. Just assume everything is broken, until it's updated.
