### ISSUE TITLE
Ignore biomes issue

### ISSUE THREAD

**Issue by mevko89** [blaxxun-boop/Farming#14]
Hi the ignore biomes option doesnt seem to work for me. Can u confirm that it works?

**Comment by NexAngelus77** [comment]
yes i also can not get the biome skip to work. it works on plains items like flax and barley but it is not working on jotun puffs and the other mistland fungi

**Comment by mevko89** [comment]
I can't plant flax and barley in dark forest, haven't gotten to mistlands yet.

**Comment by blaxxun-boop** [comment]
Tested, works perfectly fine.

Make sure your Farming skill is at a high enough level to ignore the biome requirements. Default is level 50.

**Comment by mevko89** [comment]
Um, can we reduce the default lvl, I know theres an option for it, maybe that's the problem,  I reduced thw default to like 5 and it didnt work, my skill is about 30. Ill give it a go again at lvl 50.

**Comment by blaxxun-boop** [comment]
Just FYI: There also seems to be an issue in PlanBuild or OdinsQoL that prevents players from planting the new crops, but it's not related to Farming.
