### ISSUE TITLE
Farming 2.1.7 not working - see inside for error

### ISSUE THREAD

**Issue by Syranth** [blaxxun-boop/Farming#15]
Received the following error when loading:

[Error  :   BepInEx] Could not load [Farming 2.1.7] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
Yup, moving forward, none of my mods will work with Valheim Plus.

**Comment by Syranth** [comment]
Any reason why that I should know? Is Valheim Plus bad now?
