### ISSUE TITLE
Don't work with Valheim Plus

### ISSUE THREAD

**Issue by KTLightning** [blaxxun-boop/Farming#20]
Could not load [Farming 2.1.8] because it is incompatible with: org.bepinex.plugins.valheim_plus

![Screenshot_4](https://user-images.githubusercontent.com/32077426/215295998-c8a49e05-a8f8-4f7f-8cde-5e0108fafa66.png)

**Comment by blaxxun-boop** [comment]
Yes, that is intended. If you get a message like this, this has been added purposefully by the mod author.

Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.
