### ISSUE TITLE
Doesn't work with ValheimPlus

### ISSUE THREAD

**Issue by raroDev** [blaxxun-boop/Farming#23]
The modification does not work with the ValheimPlus mod enabled. Both mods in the latest versions.
Other mods didn't work either, I'm not sure of all of them, but Passive Powers definitely didn't work.

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. Valheim Plus is a terrible mod made of mostly stolen ideas and code and the devs are huge bullies in the modding community. I am not the only one making all of my mods incompatible with Valheim Plus, other modders are already doing the same and more will follow soon. It needs to go.
