### ISSUE TITLE
Farming 2.1.8 imcompatible with valheim plus

### ISSUE THREAD

**Issue by dak4mi** [blaxxun-boop/Farming#24]
Setup:
- BepInEx 5.4.19.0
- Valheim Plus 0.9.9.1
- Farming 2.1.8

Message:
[Error  :   BepInEx] Could not load [Farming 2.1.8] because it is incompatible with: org.bepinex.plugins.valheim_plus

Will this be fixed?

**Comment by blaxxun-boop** [comment]
If you get a message like that, it means it has been placed there on purpose. Valheim Plus is a terrible mod and the devs are huge bullies in the modding community. So no, this will not get fixed.

For more info check https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by dak4mi** [comment]
> If you get a message like that, it means it has been placed there on purpose. Valheim Plus is a terrible mod and the devs are huge bullies in the modding community. So no, this will not get fixed.
> 
> For more info check [blaxxun-boop/PassivePowers#5](https://github.com/blaxxun-boop/PassivePowers/issues/5)

Thank you for the quick and detailed response.
Saw the list for replacements and going to throw out V+.
What would help me as an enduser not knowing about these troubles would be a message/link addressing the ongoing feud. So I wouldn't waste your time by creating a new issue.
Thanks for your work!
