### ISSUE TITLE
Skill stopped showing up

### ISSUE THREAD

**Issue by The-Maw** [blaxxun-boop/Farming#25]
Heya, thought this was an issue on my end so didn't think to send this in as an issue but; it seems like this mod has become incompatible with V+ since the last update, have tested by creating a new mod profile with just "Farming" and V+, and the result is that the skill doesn't show up in the skill list

Hope you can resolve this or let me know if this is a problem that's only happening on my end!

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. None of my mods will ever be compatible with Valheim Plus again.

The reason being that Valheim Plus is a terrible mod and the devs are huge bullies in the modding community. It can be easily replaced by far superior mods with far less issues. It's nothing special, causes lots of issues and is no longer maintained. It just needs to go.

For more info, see https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by The-Maw** [comment]
Cheers for the quick response, I'm sympathetic but is there any chance you could update your mod pages so people are aware of this? It's quite inconvenient to hobbyist server hosts like myself by not having awareness of very intentional incompatibilities listed on your mod page. Also are you aware of any other authors also planning to do this for V+? If there's a lot then I'll have to start looking into replacing V+.

**Comment by blaxxun-boop** [comment]
There are 5-6 mod authors who do that already and it's getting more and more. The entire modding community is just sick and tired of Valheim Plus.

Thunderstore has a flag for incompatibilities just like the dependencies already, it's just not fully implemented yet.
