### ISSUE TITLE
Skill not showing in skill list

### ISSUE THREAD

**Issue by Syranth** [blaxxun-boop/Farming#9]
Like the title. Not appearing in the list.

**Comment by virtualbjorn** [comment]
Have you started planting/farming?

**Comment by MLNW** [comment]
I have the same issue. For all other skill mods I added the skills were visible in the list before interacting with it. I will wait and see if this changes once we get the cultivator but atm I wonder if it works correctly.

**Comment by Syranth** [comment]
This issue is over 6 months old and should have been closed.
